# Generated by Django 2.0.3 on 2018-06-30 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180626_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lector',
            name='lector_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lector', to=settings.AUTH_USER_MODEL),
        ),
    ]
