# Generated by Django 2.0.3 on 2018-06-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ('name',)},
        ),
    ]
