# Generated by Django 2.0.3 on 2018-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180622_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='age_range',
        ),
        migrations.AddField(
            model_name='book',
            name='age_range',
            field=models.CharField(choices=[('F', 'Free'), ('FT', '+14'), ('ST', '+16'), ('ET', '+18')], default='F', max_length=2),
        ),
    ]
