# Generated by Django 2.0.3 on 2018-06-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180622_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='score',
            name='lector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Lector'),
        ),
    ]
