# Generated by Django 2.0.3 on 2018-06-23 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180622_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
